name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Git tag to build release from
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # - name: Login to GitHub Container Registry
      #   if: github.event_name != 'pull_request'
      #   uses: docker/login-action@v1 
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Login to Quay.io
      #   if: github.event_name != 'pull_request'
      #   uses: docker/login-action@v1
      #   with:
      #     registry: quay.io
      #     username: ${{ secrets.QUAY_USERNAME }}
      #     password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Docker meta (controller)
        id: controller-meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            quay.io/argoproj/argo-rollouts
            ghcr.io/argoproj/argo-rollouts
          tags: |
            type=semver,pattern={{version}}

      - name: Docker meta (plugin)
        id: plugin-meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            quay.io/argoproj/kubectl-argo-rollouts
            ghcr.io/argoproj/kubectl-argo-rollouts
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push (controller)
        uses: docker/build-push-action@v2
        with:
          #platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          push: false
          tags: ${{ steps.controller-meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Build and push (plugin)
        uses: docker/build-push-action@v2
        with:
          target: kubectl-argo-rollouts
          #platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          push: false
          tags: ${{ steps.plugin-meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Generate release artifacts
        run: |
          make release-plugins
          make manifests IMAGE_TAG=${{ inputs.tag }}

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/kubectl-argo-rollouts-darwin
            dist/kubectl-argo-rollouts-linux
            manifests/install.yaml
            manifests/cluster-install.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
